config/routes.rb
RailsBlog::Application.routes.draw do
  root to: "posts#index"

  resources :posts, only: [:index, :new, :create]

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    render text: "hello"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create( params[:post] )
    flash[:notice] = "Your post has now been published!"
    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash.each do |type, message| %>
  <%= message %>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<%= Rails.env %>
<%= Post.count %>

<ul>
  <% @posts.each do |post| %>
    <li><%= post.title %></li>
  <% end %>
</ul>

<%= link_to "Write Post", new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit "Submit Post" %>
<% end %>